### ISSUE TITLE
How to destroy a token ?

### ISSUE THREAD

**Issue by shafeeq2019** [ezesundayeze/forgotpassword#1]
Hello, thank you first for this repo.
How can I destroy the old JWT tokens?
If a user has changed his password because he is afraid that someone knows it, then you could still use his account if you have a token!
What would the solution be?

**Comment by nicolasricardi91** [comment]
If I'm not wrong, when you request to change your password, it verifies if there's a token created for that uid. If there's one, it deletes it. 

```
// Request password part
let token = await Token.findOne({ userId: dbUser._id });
if (token) {
    await token.deleteOne();
};
```

In that scenario there would not be two tokens for the same uid. At the end, if the user changes his password correctly, it executes this code:

```
// Change password success part
await passwordResetToken.deleteOne();
```

With this approach, there would not be two tokens for the same uid as it deletes one if exists and also if success.

**Comment by ezesundayeze** [comment]
Thanks @nashor91  for your answer. That's on point. I will close this issue as that answers the question. @shafeeq2019 in case it doesn't answer the question for you, you can re-open the issue.
